### ISSUE TITLE
Can't evaluate ''#{(1)}

### ISSUE THREAD

**Issue by amalloy** [Raynes/clojail#1] opened 2011-04-28 21:54 UTC
If the code passed to `sandbox` contains a quoted set which contains a list, there are errors about read-eval. Moving the quote inside the set so that it's in front of the list, ie `'#{'(1)}`, resolves the issue. Needs more investigation to find out what's going wrong.

**Comment by Raynes** [comment] 2011-11-26 14:29
I can't reproduce this anymore (assuming I ever did?). Closing.

**Closed as completed by Raynes** 2011-11-26 14:29 UTC

**Comment by amalloy** [comment] 2011-11-30 02:27
We did repro at some point, but I can't remember exactly what the test-case was. It's in a 4clojure Issue somewhere; i'll take a look.

**Comment by dbyrne** [comment] 2011-11-30 18:29
Link to the 4clojure issue: https://github.com/4clojure/4clojure/issues/67

**Comment by Raynes** [comment] 2011-11-30 18:35
I've been unable to reproduce this myself. If anybody can come up with a repro case that doesn't involve 4Clojure, please reply.
